### ISSUE TITLE
Add this project to `crates.io`?

### ISSUE THREAD

**Issue by qff233** [kossnikita/at32f4xx-hal#2]
Hey!

I'm new to rust embedded in particular and I am trying to write some code for the AT32F435 chip. Currently,I found your project and it seems really nice. But it is no in `crates.io`.

May I can help you complete the project?

**Comment by kossnikita** [comment]
Greetings! 

Of course you can help this project. Please check https://github.com/kossnikita/at32f4xx-hal/issues/1#issuecomment-1865433376. You can take any modules that interest you. Please let me know if you have any difficulties, I will help if I can.

About publication on crates.io. I would not like to publish while the project is in such an unfinished state. You can still use it with cargo.

```toml
[dependencies]
at32f4xx-hal = { git = "https://github.com/kossnikita/at32f4xx-hal.git" }
```
